
services:
  api:
    build: .
    container_name: fastapi
    ports:
      - "8800:8800"
  postgres:
    image: postgres:15
    container_name: postgres-Fastapi
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: FASTAPI

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:


    